services:
   jobmanager:
      user: flink:flink
      image: flink:latest
      container_name: jobmanager
      ports:
         - "8081:8081"
      command: jobmanager
      environment:
         - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
      volumes:
         - shared-tmpfs:/tmp/iceberg
         - /root/flinkcdc/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar 
         - /root/flinkcdc/flink-sql-connector-mysql-cdc-3.0.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-3.0.0.jar
         - /root/flinkcdc/iceberg-flink-runtime-1.16-1.3.jar:/opt/flink/lib/iceberg-flink-runtime-1.16-1.3.jar
         - /root/flinkcdc/flink-conf.yml:/opt/flink/conf/flink-conf.yml

   taskmanager:
      user: flink:flink
      image: flink:latest
      container_name: taskmanager
      depends_on:
         - jobmanager
      command: taskmanager
      environment:
         - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
            taskmanager.numberOfTaskSlots: 2
      volumes:
         - shared-tmpfs:/tmp/iceberg
         - /root/flinkcdc/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar 
         - /root/flinkcdc/flink-sql-connector-mysql-cdc-3.0.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-3.0.0.jar
         - /root/flinkcdc/iceberg-flink-runtime-1.16-1.3.jar:/opt/flink/lib/iceberg-flink-runtime-1.16-1.3.jar
         - /root/flinkcdc/flink-conf.yml:/opt/flink/conf/flink-conf.yml

   mysql:
      image: debezium/example-mysql:1.1
      container_name: mysql
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_USER=mysqluser
         - MYSQL_PASSWORD=mysqlpw
      volumes:
         - ./init-sql:/docker-entrypoint-initdb.d
volumes:
   shared-tmpfs:
      driver: local
      driver_opts:
         type: "tmpfs"
         device: "tmpfs"
